### ISSUE TITLE
contract generation issue

### ISSUE THREAD

**Issue by coconut-bunch** [sudoblockio/tackle-icon-contract#2]
While trying drogon with the tackle code generator, there is an error if you select "No" to "Is This a Token?" question. Tackle exits with the following error

```
drogon init                                                                     
 _ .-') _  _  .-')                                             .-') _ ,---.        
( (  OO) )( \( -O )                                           ( OO ) )|   |        
 \     .'_ ,------.  .-'),-----.   ,----.     .-'),-----. ,--./ ,--,' |   |        
 ,`'--..._)|   /`. '( OO'  .-.  ' '  .-./-') ( OO'  .-.  '|   \ |  |\ |   |        
 |  |  \  '|  /  | |/   |  | |  | |  |_( O- )/   |  | |  ||    \|  | )|   |        
 |  |   ' ||  |_.' |\_) |  |\|  | |  | .--, \\_) |  |\|  ||  .     |/ |  .'        
 |  |   / :|  .  '.'  \ |  | |  |(|  | '. (_/  \ |  | |  ||  |\    |  `--'         
 |  '--'  /|  |\  \    `'  '-'  ' |  '--'  |    `'  '-'  '|  | \   |  .--.         
 `-------' `--' '--'     `-----'   `------'       `-----' `--'  `--'  '--'         
✔ Name of the project … hello-world                                                
✔ Do you want to initialize your Drogon project with samples? … no / yes           
✔ Do you want to generate a keystore for this project? … no / yes                  
? Is this a token / NFT? No                                                        
? What is the contract name? main contract                                         
Traceback (most recent call last):                                                 
  File "/usr/local/bin/tackle", line 8, in <module>
    sys.exit(main()) 
  File "/usr/local/lib/python3.9/dist-packages/tackle/cli.py", line 130, in main
    output = tackle( 
  File "/usr/local/lib/python3.9/dist-packages/tackle/main.py", line 84, in tackle
    output = update_source(context)
  File "/usr/local/lib/python3.9/dist-packages/tackle/parser.py", line 1587, in upd
ate_source
    return run_source(context, args, kwargs, flags)
  File "/usr/local/lib/python3.9/dist-packages/tackle/parser.py", line 1051, in run
_source
    default_hook_output = context.default_hook().exec()
  File "/usr/local/lib/python3.9/dist-packages/tackle/parser.py", line 1235, in fun
ction_walk
    walk_sync(context=tmp_context, element=input_element.copy())
  File "/usr/local/lib/python3.9/dist-packages/tackle/parser.py", line 828, in walk
_sync
    walk_sync(context, v)
  File "/usr/local/lib/python3.9/dist-packages/tackle/parser.py", line 771, in walk
_sync

    run_hook(context)
  File "/usr/local/lib/python3.9/dist-packages/tackle/parser.py", line 747, in run_
hook
    parse_hook(hook_dict, Hook, context)
  File "/usr/local/lib/python3.9/dist-packages/tackle/parser.py", line 525, in pars
e_hook
    hook_output_value = run_hook_in_dir(hook)
  File "/usr/local/lib/python3.9/dist-packages/tackle/parser.py", line 329, in run_
hook_in_dir
    return hook.exec()
  File "/usr/local/lib/python3.9/dist-packages/tackle/providers/logic/hooks/match.p
y", line 77, in exec 
    raise Exception(f"Value `{self.value}` not found in {self.case.keys()}")
Exception: Value `contract` not found in <ruamel.yaml.comments.CommentedMapKeysView
 object at 0x7f0a08060610>
```

If you select "Yes" to the question, tackle generation works as expected.

more details can be found here https://github.com/icon-community/drogon/issues/26

**Comment by robcxyz** [comment]
This is a simple fix but to be clear, code generation is WIP feature and still working on the templates. So in general, I think the code generator should not be exposed till the underlying templates have been implemented.

**Comment by robcxyz** [comment]
Closing this as this issue has been fixed but comment above still stands. Added warning to help other users.
